export const HOME = '/'
export const DASHBOARD = '/dashboard'
export const PROFILE = '/profile'
export const LOGIN = '/login'
export const REGISTER ='/register'
export const PASSWORD_RESET ='/passwordreset'